# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Push Distr Application Version

on:
  push:
    tags:
      - '*'

jobs:
  push-action:
    name: Push Released Docker Compose to Distr
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Create Distr Version
        id: distr-create-version
        uses: glasskube/distr-create-version-action@v1.2.1
        with:
          api-token: ${{ secrets.DISTR_TOKEN }}
          api-base: 'https://demo.distr.sh/api/v1'
          application-id: ${{ vars.DISTR_APPLICATION_ID }}
          version-name: ${{ github.ref_name }}
          compose-file: ${{ github.workspace }}/deploy/docker-compose.yaml
          template-file: ${{ github.workspace }}/deploy/env.template

      - name: Print Application Version ID
        id: output
        run: echo "${{ steps.distr-create-version.outputs.created-version-id }}"
